### PR TITLE
fix: fixes fouc and upgrades to gatsby v2

### LINKED ISSUE #9029: Struggling to add extract-text-webpack-plugin to Gatsby v1
I'd like to preface this by saying my Webpack and Node knowledge is unfortunately very limited.  With that said, the first place I visited is the Gatsby doc page for add custom Webpack configs.  This told me to export a function from gatsby-node.js called modifyWebpackConfig.  Additionally, I would need to use webpack-configurator.

I installed this and checked out the docs for that, which literally has an example that uses extract-text-webpack-plugin.  So I copy/pasted that into the example on the Gatsby doc to get the following in my gatsby-node.js: 

```
var ExtractTextPlugin = require('extract-text-webpack-plugin')

exports.modifyWebpackConfig = ({ config, stage }) => {
  switch (stage) {
    case 'develop':
      config.loader(
        'sass',
        {
          test: /\.scss$/,
          queries: {
            css: {
              sourceMap: true,
            },
            sass: {
              sourceMap: true,
            },
          },
        },
        function(config) {
          var loaders = []

          for (var key in config.queries)
            loaders.push(key + '?' + JSON.stringify(config.queries[key]))

          config.loader = ExtractTextPlugin.extract(loaders.join('!'))

          return config
        }
      )
      break
  }

  return config
}
```
I've only got a case for develop, because I figure once that works I can add the others.  Upon running gatsby develop I get the following:

> There were errors with your webpack config:
>
> [1]
> module.loaders.8.loader
> string.base , "loader" must be a string
> 
> [2]
> module.loaders.8.queries
> object.allowUnknown , "queries" is not allowed
> 
> [3]
> module.loaders.8
> object.xor , "value" contains a conflict between exclusive peers [loaders, loader]
> 
> Your Webpack config does not appear to be valid. This could be because of
> something you added or a plugin. If you don't recognize the invalid keys listed
> above try removing plugins and rebuilding to identify the culprit.

I can add more info if needed, but I assume my code is just wrong.  If someone is able to put me out of my misery on this one I would be very grateful!

### PR DESCRIPTION
**Pull request by DSchau**
Fixes gatsbyjs/gatsby#9029

This _seems_ to fix the issues you were running into. I also upgraded you to gatsby v2.

The main issue was that the gatsby-material-ui-plugin is fairly outdated, and requires material ui v1. If you're interested, it'd be great to get some changes made to that plugin, or get the name/package rights and make the version I'm using here the official one as it's more recent/updated.

### CODE REVIEW

File: src/layouts/index.js [hunk 1]
```diff
@@ -1,53 +1,41 @@
...
 
 Layout.propTypes = {
-  children: PropTypes.func,
-  data: PropTypes.object,
+  children: PropTypes.node
 }
 
 export default Layout
-
-const graphql = (literals, ...substitutions) => {
```
Comment (DSchau) [inline src/layouts/index.js:30]: I have no idea what this was doing!

**Comment by BLBaylis** [comment]
@DSchau Thank you, what a hero!  I appreciate you taking the time to help me out!  It sounds like the Gatsby v2 upgrade was a lovely bonus as opposed to being the fix.  In which case what was the change/changes that actually resolved the problem?

**Comment by DSchau** [comment]
@BLBaylis glad to help!

Gatsby v2 is a pretty simple upgrade, so like you said, just a nice benefit!

As far as what actually fixed it, the gatsby-plugin-material-ui plugin requires material-ui@^1.0.0 (old version!), and that was breaking things. I also deleted the gatsby-ssr.js file, which was conflicting with a separate plugin (the new material-ui plugin included in this PR) because it's no longer needed.

Please do sanity check, deploy/etc, and make sure it seems to be truly fixed! Thanks for using Gatsby 💪
